# Serial libraries and packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - arrow+parquet+python@0.15.0

  gnu-stable-serial-python3:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - boost+python
      # - tensorflow@1.12.0+cuda

  gnu-intel-stable-serial:
    target_matrix:
      - gnu-stable
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - python@3.7.4

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - assimp
      - boost
      - catch ~single_header
      - deflect
      - eigen
      - fmt
      - gmsh
      - hdf5~mpi
      - highfive~mpi
      - libarchive
      - morphio
      - morpho-kit
      - openscenegraph build_type=Release
      - nlohmann-json +single_header
      - pugixml
      - random123
      - range-v3
      - rockets
      - rocksdb~static
      - spark@2.4.0+hadoop ^jdk@1.8.0_131-b11

  # gnu-stable-serial-python3:
  #   target_matrix:
  #     - gnu-stable
  #   requires:
  #     - architecture
  #     - compiler
  #     - python
  #   specs:
  #     - tensorflow@1.12.0+cuda
